export const intolerancesList = [
	{ value: "dairy", label: "Lait" },
	{ value: "egg", label: "Oeuf" },
	{ value: "gluten", label: "Gluten" },
	{ value: "grain", label: "Céréales" },
	{ value: "peanut", label: "Cacahuète" },
	{ value: "seafood", label: "Fruits de mer" },
	{ value: "sesame", label: "Sésame" },
	{ value: "shellfish", label: "Crustacés" },
	{ value: "soy", label: "Soja" },
	{ value: "sulfite", label: "Sulfites" },
	{ value: "tree-nut", label: "Fruits à coque" },
	{ value: "wheat", label: "Blé" },
];

export const cuisineList = [
	{ value: "african", label: "Africain" },
	{ value: "asian", label: "Asiatique" },
	{ value: "american", label: "Américain" },
	{ value: "british", label: "Britannique" },
	{ value: "cajun", label: "Cajun" },
	{ value: "caribbean", label: "Caribéen" },
	{ value: "chinese", label: "Chinois" },
	{ value: "eastern-european", label: "Européen de l'Est" },
	{ value: "european", label: "Européen" },
	{ value: "french", label: "Français" },
	{ value: "german", label: "Allemand" },
	{ value: "greek", label: "Grec" },
	{ value: "indian", label: "Indien" },
	{ value: "irish", label: "Irlandais" },
	{ value: "italian", label: "Italien" },
	{ value: "japanese", label: "Japonais" },
	{ value: "jewish", label: "Juif" },
	{ value: "korean", label: "Coréen" },
	{ value: "latin-american", label: "Latin Américain" },
	{ value: "mediterranean", label: "Méditerranéen" },
	{ value: "mexican", label: "Mexicain" },
	{ value: "middle-eastern", label: "Moyen-Oriental" },
	{ value: "nordic", label: "Nordique" },
	{ value: "southern", label: "Sudiste" },
	{ value: "spanish", label: "Espagnol" },
	{ value: "thai", label: "Thaïlandais" },
	{ value: "vietnamese", label: "Vietnamiens" },
];

export const dietList = [
	{ value: "gluten-free", label: "Sans Gluten" },
	{ value: "ketogenic", label: "Cétogène" },
	{ value: "vegetarian", label: "Végétarien" },
	{ value: "lacto-vegetarian", label: "Lacto-Végétarien" },
	{ value: "ovo-vegetarian", label: "Ovo-Végétarien" },
	{ value: "vegan", label: "Végan" },
	{ value: "pescetarian", label: "Pescétarien" },
	{ value: "paleo", label: "Paléo" },
	{ value: "primal", label: "Primal" },
	{ value: "low-fodmap", label: "Faible en FODMAP" },
	{ value: "whole30", label: "Whole30" },
];

export const excludeIngredientsList = [
	{ value: "gluten", label: "Gluten" },
	{ value: "dairy", label: "Produits laitiers" },
	{ value: "soy", label: "Soja" },
	{ value: "peanuts", label: "Cacahuètes" },
	{ value: "tree_nuts", label: "Fruits à coque" },
	{ value: "fish", label: "Poisson" },
	{ value: "shellfish", label: "Crustacés" },
	{ value: "eggs", label: "Œufs" },
	{ value: "wheat", label: "Blé" },
	{ value: "corn", label: "Maïs" },
	{ value: "sugar", label: "Sucre" },
	{ value: "caffeine", label: "Caféine" },
	{ value: "chocolate", label: "Chocolat" },
	{ value: "tomato", label: "Tomates" },
	{ value: "potatoes", label: "Pommes de terre" },
	{ value: "onion", label: "Oignons" },
	{ value: "garlic", label: "Ail" },
	{ value: "carrot", label: "Carottes" },
	{ value: "apple", label: "Pommes" },
	{ value: "banana", label: "Bananes" },
	{ value: "peach", label: "Pêches" },
	{ value: "coconut", label: "Noix de coco" }
];
